global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'x-api-app1'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ '192.168.200.1:8091' ]
  - job_name: 'x-api-app2'
    static_configs:
      - targets: [ '192.168.200.1:9182' ]